### PR TITLE
Update README.

### PR DESCRIPTION
**Pull request by thealmarty**
Add more detail instructions and remove section about reading input from file.

### CODE REVIEW

**Review by mratsim — COMMENTED** [review]
I think valida run should still appear, but the build command should be `cargo +valida build --release` and so the run command should be

```
valida> valida run ./target/delendum-unknown-baremetal-gnu/release/fibonacci log
```

Alternatively we delete this repo and move the additional instructions in the `rust-examples` as we have already lots of examples in the rust-examples repo.

**Comment by thealmarty** [comment]
Updated to latest toolchain. It now compiles with the latest toolchain for the upcoming release. TODO: add more docker instructions for Mac and for the newly added cargo subcommands.

**Comment by morganthomas** [comment]
Thanks @thealmarty ! This looks good to me. Let's hold off on merging this until we have released `0.6.0-alpha`. I have marked this as a draft so that it will not be merged by accident.

**Comment by thealmarty** [comment]
> Thanks @thealmarty ! This looks good to me. Let's hold off on merging this until we have released `0.6.0-alpha`. I have marked this as a draft so that it will not be merged by accident.

Should I merge it to a new `develop` branch? The `main` branch will have all tagged releases and we develop on the `develop` branch.

**Review by morganthomas — APPROVED** [review]

**Comment by morganthomas** [comment]
Thanks, @thealmarty , that's a good suggestion. I created a `develop` branch and am now going to merge this PR to it.

**Pull request merged**
